Updated bootstrap

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,12 +1,21 @@
 #!/bin/sh
 
-if [ -d "./env" ]
+if ! [ -d "./env" ]
 then
-  source ./env/bin/activate
-else
-  python3 -m venv env
-  . ./env/bin/activate
+  echo "You are missing a virtual Environment"
+  echo "run the following commands:"
+  echo "python3 -m venv env"
+  echo ". ./env/bin/activate"
+  exit
+fi
+
+if [[ "$VIRTUAL_ENV" != "" ]]
+then
   pip3 install -r requirements.txt
+else
+  echo "CAREFUL YOU ARE NOT IN YOUR VIRTUAL ENV"
+  echo "To enter your virtual env use the following command"
+  echo ". ./env/bin/activate"
 fi
 
 
